AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance and output its details.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Instance Configuration"
        Parameters:
          - InstanceType
          - KeyName
    ParameterLabels:
      InstanceType:
        default: "EC2 Instance Type"
      KeyName:
        default: "Key Pair Name"

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: "This is the primary EC2 instance resource."
      Purpose: "For testing and demonstration purposes."
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c02fb55956c7d316 # Replace with a valid AMI ID for your region
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      Comment: "This security group allows SSH and HTTP access."
      Purpose: "Defines network access rules for the EC2 instance."
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          
Outputs:
  InstanceId:
    Description: The Instance ID of the created EC2 instance
    Value: !Ref MyEC2Instance

  InstancePublicIp:
    Description: The public IP address of the created EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
